export * from './account.service';
import { AccountService } from './account.service';
export * from './course.service';
import { CourseService } from './course.service';
export * from './courseInstance.service';
import { CourseInstanceService } from './courseInstance.service';
export * from './pet.service';
import { PetService } from './pet.service';
export * from './studentController.service';
import { StudentControllerService } from './studentController.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [AccountService, CourseService, CourseInstanceService, PetService, StudentControllerService, UserService];
