/**
 * Spring Boot REST API - Student Service Management App
 * *<b>To authenticate yourself do the following:</b>* 1. Use the API endpoints with approprite requests. 2. For API calls, use the token value in a HTTP request header as follows: \"Bearer [token value]\". For Swagger you use the Authorize button and insert \"Bearer [token value]\" in the text input.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterRequest { 
    email?: string;
    firstName?: string;
    lastName?: string;
    role?: RegisterRequest.RoleEnum;
}
export namespace RegisterRequest {
    export type RoleEnum = 'STUDENT' | 'PROFESSOR' | 'ASSISTANT';
    export const RoleEnum = {
        Student: 'STUDENT' as RoleEnum,
        Professor: 'PROFESSOR' as RoleEnum,
        Assistant: 'ASSISTANT' as RoleEnum
    };
}


